backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
  - name: product
    label: Product
    folder: product
    create: true
    fields:
      - { name: path, label: Path }
      - { name: productName, label: Name, widget: "string" }
      - { name: description, label: Description, widget: "string" }
      - { name: price, label: Price, widget: "string" }
      - { name: image, label: Image, widget: "image" }
      - { name: altText, label: Alt Text, widget: "string" }
      - { name: ratings, label: Ratings, widget: "string" }